const ar = {
  loginButton: "تسجيل الدخول",
  LoginNow: "التسجيل الدخول الآن",
  FreshChart: "فريش شارت",
  RegisterNow: "سجل الآن",
  RegisterButton: "تسجيل",
  SubmitButton: "إرسال",
  dontHaveAccount: "ليس لديك حساب",
  pageNotFound: "عذراً، الصفحة التي طلبتها غير موجودة",
  AlreadyHaveAccount : "هل لديك حساب؟",
  goHome: "الذهاب إلى الصفحة الرئيسية",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  confirmPassword: "تأكيد كلمة المرور",
  phone: "الهاتف",
  about: "من نحن",
  home: "الصفحة الرئيسية",
  privacy: "الخصوصية",
  textFooter: "© 2025 فريش شارت. جميع الحقوق محفوظة.",
  contact: "اتصل بنا",
  Wishlist: "قائمة المفضله",
  Cart: "عربة التسوق",
  Search: "بحث عن المنتجات",
  SearchPlaceholder: "ابحث عن المنتجات...",
  Logout: "تسجيل خروج",
  AddToCartButton: "أضف إلى السلة",
  removefromcart : "إزالة من السلة",
  removefromfavourite : 'إزالة من المفضلة',
  snackbar: "تمت إزالة العنصر من السلة",
  snackbar1: "تمت إضافة العنصر إلى السلة",
    snackbar2: "تمت إضافة العنصر إلى المفضلة",
    snackbar3: "تمت إزالة العنصر من المفضلة",
  currency : "ج.م",
  LastUpdated: 'اخر تحديث',
  PleaseEnterYourAddress: 'من فضلك أدخل عنوانك',
  AddressMustBeAtLeast8CharactersLong: 'يجب أن يكون العنوان 8 أحرف على الأقل',
  AddressMustContainBothLettersAndNumbers: 'يجب أن يحتوي العنوان على أحرف وأرقام',
  StartShoppingButton: "ابدأ التسوق",
  Loading: "جار التحميل...",
  YourCartIsEmpty: "سلة التسوق الخاصة بك فارغة",
  Addyourfavouriteitemstoyourcart: " أضف العناصر المفضلة لديك إلى سلة التسوق الخاصة بك",
  Addtofavourite: "أضف إلى المفضلة",
  Remove: "إزالة",
  MyWishlist: "قائمة المفضلات الخاصة بي",
  MyCart : "عربة التسوق الخاصة بي",
  Yourwishlistisempty: "قائمة المفضلات الخاصة بك فارغة",
  undertextwishlist: "ابدأ في إضافة منتجاتك المفضلة للحفظ ومراجعتها لاحقًا.",
  deleteItems: "حذف العناصر",
  AllItemsDeletedFromCart: "تم حذف جميع العناصر من السلة",
  backtohome: "العودة إلى الصفحة الرئيسية",
  Admin: "المسؤول",
  item : "عنصر",
  items : "عناصر",
  orderplacedsuccessfully: "تم تقديم الطلب بنجاح",
  notfound: "لم نتمكن من العثور على ما كنت تبحث عنه",
  NoProductsAvailable: "لا توجد منتجات متاحة",
  Keepcalmandsearchagain: "اهدأ وابحث مرة أخرى.", 
  otherproducts: "لدينا العديد من المنتجات الأخرى التي ستعجبك!",
  nodata:"يبدو أنه لا توجد منتجات في متجرنا في الوقت الحالي. يرجى التحقق مرة أخرى لاحقًا.",
  continueShopping: "استمر في التسوق",
  makeanorder: " قم بعمل طلب", 
  Dashboard: "لوحة القيادة",
  TotalProducts: "إجمالي المنتجات",
  Categories: "الفئات",
  Orders: "الطلبات",
  Users: "المستخدمون",
  Products: "المنتجات",
  Edit: "تعديل",
  Delete: "حذف",
  AddProduct: "إضافة منتج",
  AddCategory: "إضافة فئة",
  EditCategory: "تعديل الفئة",
  EditProduct: "تعديل المنتج",
  CategoryName: "اسم الفئة",
  Title: "العنوان",
  Price: "السعر",
  Image: "الصورة",
  Description: "الوصف",
  SubCategory: "الفئة الفرعية",
  Category: "الفئة",
  Slug: "الاسم المختصر",
  CreatedAt: "تاريخ الإنشاء",
  Actions: "الإجراءات",
  Cancel: "إلغاء",
  Save: "حفظ",
  Name: "الاسم",
  Customer: "العميل",
  Stockstatus: "حالة المخزون",
  Status: "الحالة",
  TotalPrice: "السعر الإجمالي",
  ShippingAddress: "عنوان الشحن",
  UserName: "اسم المستخدم",
  TotalCategories: "إجمالي الفئات",
  TotalOrders: "إجمالي الطلبات",
  TotalUsers: "إجمالي المستخدمين",
  shipped: "تم الشحن",
  delivered: "تم التوصيل",
  processing: "قيد المعالجة",
  canceled: "ملغي",
};

export default ar;
