const ar = {
  loginButton: "تسجيل الدخول",
  LoginNow: "التسجيل الدخول الآن",
  FreshChart: "فريش شارت",
  RegisterNow: "سجل الآن",
  RegisterButton: "تسجيل",
  SubmitButton: "إرسال",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  confirmPassword: "تأكيد كلمة المرور",
  phone: "الهاتف",
  home: "الصفحة الرئيسية",
  about: "حول",
  contact: "اتصل بنا",
  Wishlist: "قائمة المفضله",
  Cart: "عربة التسوق",
  Search: "بحث عن المنتجات",
  Logout: "تسجيل خروج",
  AddToCartButton: "أضف إلى السلة",
  StartShoppingButton: "ابدأ التسوق",
  YourCartIsEmpty: "سلة التسوق الخاصة بك فارغة",
  Addyourfavouriteitemstoyourcart: " أضف العناصر المفضلة لديك إلى سلة التسوق الخاصة بك",
  MyWishlist: "قائمة المفضلات الخاصة بي",
  Yourwishlistisempty: "قائمة المفضلات الخاصة بك فارغة",
  undertextwishlist: "ابدأ في إضافة منتجاتك المفضلة للحفظ ومراجعتها لاحقًا.",
  deleteItems: "حذف العناصر",
  Admin: "المسؤول",
  items : "عناصر",
  makeanorder: " قم بعمل طلب", 
  Dashboard: "لوحة القيادة",
  TotalProducts: "إجمالي المنتجات",
  Categories: "الفئات",
  Orders: "الطلبات",
  Users: "المستخدمون",
  Products: "المنتجات",
  Edit: "تعديل",
  Delete: "حذف",
  AddProduct: "إضافة منتج",
  AddCategory: "إضافة فئة",
  Title: "العنوان",
  Price: "السعر",
  Image: "الصورة",
  Description: "الوصف",
  SubCategory: "الفئة الفرعية",
  Category: "الفئة",
  Slug: "الاسم المختصر",
  CreatedAt: "تاريخ الإنشاء",
  Actions: "الإجراءات",
  Name: "الاسم",
  Customer: "العميل",
  Status: "الحالة",
  TotalPrice: "السعر الإجمالي",
  ShippingAddress: "عنوان الشحن",
  UserName: "اسم المستخدم",
};

export default ar;
