const en = {
  loginButton: "Login",
  LoginNow: "Login Now",
  FreshChart: "FreshChart",
  RegisterNow: "Register Now",
  RegisterButton: "Register",
  SubmitButton: "Submit",
  dontHaveAccount: "Don't have an account",
  AlreadyHaveAccount : "Already have an account?",
  pageNotFound: "Sorry, the page you requested was not found",
  goHome: "Go to Home",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  phone: "Phone",
  home: "Home",
  about: "About",
  privacy: "Privacy",
  textFooter: "© 2025 FreshCart. All rights reserved.",
  contact: "Contact",
  Wishlist: "Wishlist",
  Loading: "Loading...",
  Cart: "Cart",
  Search: "Search Products",
  SearchPlaceholder: "Search products...",
  Logout: "Logout",
  AddToCartButton: "Add To Cart",
  removefromcart: "Remove From Cart",
  removefromfavourite: 'Remove from Favourite',
  snackbar: "Item removed from cart",
  snackbar1: "Item added to cart",
  snackbar2: "Item added to favourite",
  snackbar3: "Item removed from favourite",
  currency: "EGP",
  LastUpdated: 'Last Updated',
  PleaseEnterYourAddress: 'Please enter your address',
  AddressMustBeAtLeast8CharactersLong: 'Address must be at least 8 characters long',
  AddressMustContainBothLettersAndNumbers: 'Address must contain both letters and numbers',
  StartShoppingButton: "Start Shopping",
  YourCartIsEmpty: "Your Cart is Empty",
  Addyourfavouriteitemstoyourcart: "Add your favourite items to your cart",
  Addtofavourite: "Add to favourite",
  Remove: "Remove",
  MyWishlist: "My Wishlist",
  MyCart: "My Cart",
  Yourwishlistisempty: "Your wishlist is empty",
  undertextwishlist: "start adding your favorite products to save and review them later.",
  deleteItems: "Delete Items",
  AllItemsDeletedFromCart: "All items deleted from cart",
  backtohome: "Back to Home",
  Admin: "Admin",
  item: "item",
  items: "items",
  orderplacedsuccessfully: "Order Placed Successfully!",
  notfound: "We couldn't find what you were looking for",
  NoProductsAvailable: "No Products Available",
  Keepcalmandsearchagain: "Keep calm and search again.",
  otherproducts: "We have SO many other products that you will like!",
  nodata: "It looks like there are no products in our store right now. Please check back later.",
  continueShopping: "CONTINUE SHOPPING",
  makeanorder: "Make an Order",
  Dashboard: "Dashboard",
  Categories: "Categories",
  Orders: "Orders",
  Users: "Users",
  Products: "Products",
  Edit: "Edit",
  Delete: "Delete",
  AddProduct: "Add Product",
  AddCategory: "Add Category",
  EditCategory: "Edit Category",
  EditProduct: "Edit Product",
  CategoryName: "Category Name",
  AddSubCategory: "Add SubCategory",
  Title: "Title",
  Price: "Price",
  Image: "Image",
  Description: "Description",
  SubCategory: "SubCategory",
  Category: "Category",
  Slug: "Slug",
  CreatedAt: "CreatedAt",
  Actions: "Actions",
  Cancel: "Cancel",
  Save: "Save",
  Name: "Name",
  Customer: "Customer",
  Stockstatus: "Stock status",
  Status: "Status",
  TotalPrice: "Total Price",
  ShippingAddress: "Shipping Address",
  UserName: "User Name",
  TotalProducts: "Total Products",
  TotalCategories: "Total Categories",
  TotalOrders: "Total Orders",
  TotalUsers: "Total Users",
  shipped: "shipped",
  delivered: "delivered",
  processing: "processing",
  canceled: "canceled",
};

export default en;
