const en = {
  loginButton: "Login",
  LoginNow: "Login Now",
  FreshChart: "FreshChart",
  RegisterNow: "Register Now",
  RegisterButton: "Register",
  SubmitButton: "Submit",
  name: "Name",
  email: "Email",
  password: "Password",
  confirmPassword: "Confirm Password",
  phone: "Phone",
  home: "Home",
  about: "About",
  contact: "Contact",
  Wishlist: "Wishlist",
  Cart: "Cart",
  Search: "Search Products",
  Logout: "Logout",
  AddToCartButton: "Add To Cart",
  StartShoppingButton: "Start Shopping",
  YourCartIsEmpty: "Your Cart is Empty",
  Addyourfavouriteitemstoyourcart: "Add your favourite items to your cart",
  MyWishlist: "My Wishlist",
  Yourwishlistisempty: "Your wishlist is empty",
  undertextwishlist: "tart adding your favorite products to save and review them later.",
  deleteItems: "Delete Items",
  Admin: "Admin",
  items : "items",
  makeanorder: "Make an Order", 
  Dashboard: "Dashboard",
  TotalProducts: "Total Products",
  Categories: "Categories",
  Orders: "Orders",
  Users: "Users",
  Products: "Products",
  Edit: "Edit",
  Delete: "Delete",
  AddProduct: "Add Product",
  AddCategory: "Add Category",
  AddSubCategory: "Add SubCategory",
  Title: "Title",
  Price: "Price",
  Image: "Image",
  Description: "Description",
  SubCategory: "SubCategory",
  Category: "Category",
  Slug: "Slug",
  CreatedAt: "CreatedAt",
  Actions: "Actions",
  Name: "Name",
  Customer: "Customer",
  Status: "Status",
  TotalPrice: "Total Price",
  ShippingAddress: "Shipping Address",
  UserName: "User Name",
};

export default en;
